name: file_saver_ffi
description: "A high-performance file saver for Flutter using FFI and JNI. Effortlessly save to gallery (images/videos) or device storage with original quality and custom album support."
version: 0.9.1
homepage: https://github.com/vanvixi/file_saver_ffi.flutter
repository: https://github.com/vanvixi/file_saver_ffi.flutter
issue_tracker: https://github.com/vanvixi/file_saver_ffi.flutter
topics:
  - file-saver
  - gallery-saver
  - saver
  - ffi
  - jni

screenshots:
  - description: "File Saver Ffi"
    path: screenshots/thumbnail.jpg

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^2.2.0
  jni: ^1.0.0
  path: ^1.9.1
  path_provider_windows: ^2.3.0
  xdg_directories: ^1.1.0
  dir_picker: ^0.4.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1
  jnigen: ^0.16.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: com.vanvixi.file_saver_ffi
        pluginClass: FileSaverFfiPlugin
        dartPluginClass: FileSaverAndroid
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: FileSaverDarwin
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: FileSaverDarwin
      windows:
        dartPluginClass: FileSaverWindows
      linux:
        dartPluginClass: FileSaverLinux
      web:
        pluginClass: FileSaverWeb
        fileName: file_saver_ffi.dart
