// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.vanvixi.file_saver_ffi.FileSaver`
class FileSaver extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<FileSaver> $type;

  @jni$_.internal
  FileSaver.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/FileSaver',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileSaver?> nullableType =
      $FileSaver$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileSaver> type = $FileSaver$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileSaver(jni$_.JObject context) {
    final _$context = context.reference;
    return FileSaver.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_saveBytes = _class.instanceMethodId(
    r'saveBytes',
    r'([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _saveBytes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public suspend fun saveBytes(fileData: kotlin.ByteArray, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, subDir: kotlin.String?, conflictMode: kotlin.Int): com.vanvixi.file_saver_ffi.models.SaveResult`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<SaveResult> saveBytes(
    jni$_.JByteArray bs,
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString? string3,
    int i,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$bs = bs.reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final $r = _saveBytes(
      reference.pointer,
      _id_saveBytes as jni$_.JMethodIDPtr,
      _$bs.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      i,
      _$continuation.pointer,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
        jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)),
      );
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e = jni$_.failureExceptionField.get(
          $o,
          const jni$_.$JObject$Type$(),
        );
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<SaveResult>(const $SaveResult$Type$(), releaseOriginal: true);
  }
}

final class $FileSaver$NullableType$ extends jni$_.JType<FileSaver?> {
  @jni$_.internal
  const $FileSaver$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/FileSaver;';

  @jni$_.internal
  @core$_.override
  FileSaver? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : FileSaver.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<FileSaver?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FileSaver$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FileSaver$NullableType$) &&
        other is $FileSaver$NullableType$;
  }
}

final class $FileSaver$Type$ extends jni$_.JType<FileSaver> {
  @jni$_.internal
  const $FileSaver$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/FileSaver;';

  @jni$_.internal
  @core$_.override
  FileSaver fromReference(jni$_.JReference reference) =>
      FileSaver.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<FileSaver?> get nullableType => const $FileSaver$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FileSaver$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FileSaver$Type$) && other is $FileSaver$Type$;
  }
}

/// from: `com.vanvixi.file_saver_ffi.models.SaveResult$Companion`
class SaveResult$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<SaveResult$Companion> $type;

  @jni$_.internal
  SaveResult$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/models/SaveResult$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SaveResult$Companion?> nullableType =
      $SaveResult$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SaveResult$Companion> type =
      $SaveResult$Companion$Type$();
  static final _id_success = _class.instanceMethodId(
    r'success',
    r'(Ljava/lang/String;Ljava/lang/String;)Lcom/vanvixi/file_saver_ffi/models/SaveResult;',
  );

  static final _success =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun success(filePath: kotlin.String, uri: kotlin.String): com.vanvixi.file_saver_ffi.models.SaveResult`
  /// The returned object must be released after use, by calling the [release] method.
  SaveResult success(jni$_.JString string, jni$_.JString string1) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _success(
      reference.pointer,
      _id_success as jni$_.JMethodIDPtr,
      _$string.pointer,
      _$string1.pointer,
    ).object<SaveResult>(const $SaveResult$Type$());
  }

  static final _id_failure = _class.instanceMethodId(
    r'failure',
    r'(Ljava/lang/String;Ljava/lang/String;)Lcom/vanvixi/file_saver_ffi/models/SaveResult;',
  );

  static final _failure =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun failure(errorCode: kotlin.String, errorMessage: kotlin.String): com.vanvixi.file_saver_ffi.models.SaveResult`
  /// The returned object must be released after use, by calling the [release] method.
  SaveResult failure(jni$_.JString string, jni$_.JString string1) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _failure(
      reference.pointer,
      _id_failure as jni$_.JMethodIDPtr,
      _$string.pointer,
      _$string1.pointer,
    ).object<SaveResult>(const $SaveResult$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SaveResult$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return SaveResult$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $SaveResult$Companion$NullableType$
    extends jni$_.JType<SaveResult$Companion?> {
  @jni$_.internal
  const $SaveResult$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/vanvixi/file_saver_ffi/models/SaveResult$Companion;';

  @jni$_.internal
  @core$_.override
  SaveResult$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : SaveResult$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SaveResult$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SaveResult$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SaveResult$Companion$NullableType$) &&
        other is $SaveResult$Companion$NullableType$;
  }
}

final class $SaveResult$Companion$Type$
    extends jni$_.JType<SaveResult$Companion> {
  @jni$_.internal
  const $SaveResult$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/vanvixi/file_saver_ffi/models/SaveResult$Companion;';

  @jni$_.internal
  @core$_.override
  SaveResult$Companion fromReference(jni$_.JReference reference) =>
      SaveResult$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SaveResult$Companion?> get nullableType =>
      const $SaveResult$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SaveResult$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SaveResult$Companion$Type$) &&
        other is $SaveResult$Companion$Type$;
  }
}

/// from: `com.vanvixi.file_saver_ffi.models.SaveResult`
class SaveResult extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<SaveResult> $type;

  @jni$_.internal
  SaveResult.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/models/SaveResult',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SaveResult?> nullableType =
      $SaveResult$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SaveResult> type = $SaveResult$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/vanvixi/file_saver_ffi/models/SaveResult$Companion;',
  );

  /// from: `static public final com.vanvixi.file_saver_ffi.models.SaveResult$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static SaveResult$Companion get Companion =>
      _id_Companion.get(_class, const $SaveResult$Companion$Type$());

  static final _id_new$ = _class.constructorId(
    r'(ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(boolean z, java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.String string3)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SaveResult(
    bool z,
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JString? string3,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    return SaveResult.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        z ? 1 : 0,
        _$string.pointer,
        _$string1.pointer,
        _$string2.pointer,
        _$string3.pointer,
      ).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(boolean z, java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.String string3, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SaveResult.new$1(
    bool z,
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JString? string3,
    int i,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return SaveResult.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        z ? 1 : 0,
        _$string.pointer,
        _$string1.pointer,
        _$string2.pointer,
        _$string3.pointer,
        i,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }

  static final _id_isSuccess = _class.instanceMethodId(r'isSuccess', r'()Z');

  static final _isSuccess =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final boolean isSuccess()`
  bool isSuccess() {
    return _isSuccess(
      reference.pointer,
      _id_isSuccess as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_getFilePath = _class.instanceMethodId(
    r'getFilePath',
    r'()Ljava/lang/String;',
  );

  static final _getFilePath =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getFilePath()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getFilePath() {
    return _getFilePath(
      reference.pointer,
      _id_getFilePath as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getUri = _class.instanceMethodId(
    r'getUri',
    r'()Ljava/lang/String;',
  );

  static final _getUri =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getUri()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getUri() {
    return _getUri(
      reference.pointer,
      _id_getUri as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getErrorMessage = _class.instanceMethodId(
    r'getErrorMessage',
    r'()Ljava/lang/String;',
  );

  static final _getErrorMessage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getErrorMessage()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getErrorMessage() {
    return _getErrorMessage(
      reference.pointer,
      _id_getErrorMessage as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getErrorCode = _class.instanceMethodId(
    r'getErrorCode',
    r'()Ljava/lang/String;',
  );

  static final _getErrorCode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getErrorCode()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getErrorCode() {
    return _getErrorCode(
      reference.pointer,
      _id_getErrorCode as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_component1 = _class.instanceMethodId(r'component1', r'()Z');

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.Boolean`
  bool component1() {
    return _component1(
      reference.pointer,
      _id_component1 as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_component2 = _class.instanceMethodId(
    r'component2',
    r'()Ljava/lang/String;',
  );

  static final _component2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component2(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component2() {
    return _component2(
      reference.pointer,
      _id_component2 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_component3 = _class.instanceMethodId(
    r'component3',
    r'()Ljava/lang/String;',
  );

  static final _component3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component3(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component3() {
    return _component3(
      reference.pointer,
      _id_component3 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_component4 = _class.instanceMethodId(
    r'component4',
    r'()Ljava/lang/String;',
  );

  static final _component4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component4(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component4() {
    return _component4(
      reference.pointer,
      _id_component4 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_component5 = _class.instanceMethodId(
    r'component5',
    r'()Ljava/lang/String;',
  );

  static final _component5 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component5(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component5() {
    return _component5(
      reference.pointer,
      _id_component5 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_copy = _class.instanceMethodId(
    r'copy',
    r'(ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/vanvixi/file_saver_ffi/models/SaveResult;',
  );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(isSuccess: kotlin.Boolean, filePath: kotlin.String?, uri: kotlin.String?, errorMessage: kotlin.String?, errorCode: kotlin.String?): com.vanvixi.file_saver_ffi.models.SaveResult`
  /// The returned object must be released after use, by calling the [release] method.
  SaveResult copy(
    bool z,
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JString? string3,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    return _copy(
      reference.pointer,
      _id_copy as jni$_.JMethodIDPtr,
      z ? 1 : 0,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
    ).object<SaveResult>(const $SaveResult$Type$());
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }
}

final class $SaveResult$NullableType$ extends jni$_.JType<SaveResult?> {
  @jni$_.internal
  const $SaveResult$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/models/SaveResult;';

  @jni$_.internal
  @core$_.override
  SaveResult? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : SaveResult.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SaveResult?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SaveResult$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SaveResult$NullableType$) &&
        other is $SaveResult$NullableType$;
  }
}

final class $SaveResult$Type$ extends jni$_.JType<SaveResult> {
  @jni$_.internal
  const $SaveResult$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/models/SaveResult;';

  @jni$_.internal
  @core$_.override
  SaveResult fromReference(jni$_.JReference reference) =>
      SaveResult.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SaveResult?> get nullableType =>
      const $SaveResult$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SaveResult$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SaveResult$Type$) &&
        other is $SaveResult$Type$;
  }
}
