// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.vanvixi.file_saver_ffi.FileSaver$Companion`
extension type FileSaver$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/FileSaver$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileSaver$Companion> type =
      $FileSaver$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileSaver$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<FileSaver$Companion>();
  }
}

extension FileSaver$Companion$$Methods on FileSaver$Companion {
  static final _id_get$storagePermissionHandler = FileSaver$Companion._class
      .instanceMethodId(
        r'getStoragePermissionHandler',
        r'()Lcom/vanvixi/file_saver_ffi/utils/StoragePermissionHandler;',
      );

  static final _get$storagePermissionHandler =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.vanvixi.file_saver_ffi.utils.StoragePermissionHandler getStoragePermissionHandler()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get storagePermissionHandler {
    return _get$storagePermissionHandler(
      reference.pointer,
      _id_get$storagePermissionHandler.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_set$storagePermissionHandler = FileSaver$Companion._class
      .instanceMethodId(
        r'setStoragePermissionHandler',
        r'(Lcom/vanvixi/file_saver_ffi/utils/StoragePermissionHandler;)V',
      );

  static final _set$storagePermissionHandler =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setStoragePermissionHandler(com.vanvixi.file_saver_ffi.utils.StoragePermissionHandler storagePermissionHandler)`
  set storagePermissionHandler(jni$_.JObject? storagePermissionHandler) {
    final _$storagePermissionHandler =
        storagePermissionHandler?.reference ?? jni$_.jNullReference;
    _set$storagePermissionHandler(
      reference.pointer,
      _id_set$storagePermissionHandler.pointer,
      _$storagePermissionHandler.pointer,
    ).check();
  }
}

final class $FileSaver$Companion$Type$
    extends jni$_.JType<FileSaver$Companion> {
  @jni$_.internal
  const $FileSaver$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/FileSaver$Companion;';
}

/// from: `com.vanvixi.file_saver_ffi.FileSaver`
extension type FileSaver._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/FileSaver',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileSaver> type = $FileSaver$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/vanvixi/file_saver_ffi/FileSaver$Companion;',
  );

  /// from: `static public final com.vanvixi.file_saver_ffi.FileSaver$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static FileSaver$Companion get Companion =>
      _id_Companion.get(_class, FileSaver$Companion.type)
          as FileSaver$Companion;

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileSaver() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<FileSaver>();
  }
}

extension FileSaver$$Methods on FileSaver {
  static final _id_canOpenFile = FileSaver._class.instanceMethodId(
    r'canOpenFile',
    r'(Ljava/lang/String;)Z',
  );

  static final _canOpenFile =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun canOpenFile(uri: kotlin.String): kotlin.Boolean`
  core$_.bool canOpenFile(jni$_.JString string) {
    final _$string = string.reference;
    return _canOpenFile(
      reference.pointer,
      _id_canOpenFile.pointer,
      _$string.pointer,
    ).boolean;
  }

  static final _id_openFile = FileSaver._class.instanceMethodId(
    r'openFile',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _openFile =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun openFile(uri: kotlin.String, mimeType: kotlin.String?): kotlin.Unit`
  void openFile(jni$_.JString string, jni$_.JString? string1) {
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _openFile(
      reference.pointer,
      _id_openFile.pointer,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_cancelOperation = FileSaver._class.instanceMethodId(
    r'cancelOperation',
    r'(J)V',
  );

  static final _cancelOperation =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int64,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun cancelOperation(operationId: kotlin.Long): kotlin.Unit`
  void cancelOperation(core$_.int j) {
    _cancelOperation(reference.pointer, _id_cancelOperation.pointer, j).check();
  }

  static final _id_saveBytes = FileSaver._class.instanceMethodId(
    r'saveBytes',
    r'([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)J',
  );

  static final _saveBytes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveBytes(fileData: kotlin.ByteArray, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, saveLocationIndex: kotlin.Int, subDir: kotlin.String?, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Long`
  core$_.int saveBytes(
    jni$_.JByteArray bs,
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    core$_.int i,
    jni$_.JString? string3,
    core$_.int i1,
    ProgressCallback progressCallback,
  ) {
    final _$bs = bs.reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$progressCallback = progressCallback.reference;
    return _saveBytes(
      reference.pointer,
      _id_saveBytes.pointer,
      _$bs.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      i,
      _$string3.pointer,
      i1,
      _$progressCallback.pointer,
    ).long;
  }

  static final _id_saveFile = FileSaver._class.instanceMethodId(
    r'saveFile',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)J',
  );

  static final _saveFile =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveFile(filePath: kotlin.String, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, saveLocationIndex: kotlin.Int, subDir: kotlin.String?, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Long`
  core$_.int saveFile(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    core$_.int i,
    jni$_.JString? string4,
    core$_.int i1,
    ProgressCallback progressCallback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4?.reference ?? jni$_.jNullReference;
    final _$progressCallback = progressCallback.reference;
    return _saveFile(
      reference.pointer,
      _id_saveFile.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      i,
      _$string4.pointer,
      i1,
      _$progressCallback.pointer,
    ).long;
  }

  static final _id_saveNetwork = FileSaver._class.instanceMethodId(
    r'saveNetwork',
    r'(Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)J',
  );

  static final _saveNetwork =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveNetwork(url: kotlin.String, headersJson: kotlin.String?, timeoutMs: kotlin.Int, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, saveLocationIndex: kotlin.Int, subDir: kotlin.String?, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Long`
  core$_.int saveNetwork(
    jni$_.JString string,
    jni$_.JString? string1,
    core$_.int i,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JString string4,
    core$_.int i1,
    jni$_.JString? string5,
    core$_.int i2,
    ProgressCallback progressCallback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4.reference;
    final _$string5 = string5?.reference ?? jni$_.jNullReference;
    final _$progressCallback = progressCallback.reference;
    return _saveNetwork(
      reference.pointer,
      _id_saveNetwork.pointer,
      _$string.pointer,
      _$string1.pointer,
      i,
      _$string2.pointer,
      _$string3.pointer,
      _$string4.pointer,
      i1,
      _$string5.pointer,
      i2,
      _$progressCallback.pointer,
    ).long;
  }

  static final _id_saveBytesAs = FileSaver._class.instanceMethodId(
    r'saveBytesAs',
    r'([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)J',
  );

  static final _saveBytesAs =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveBytesAs(fileData: kotlin.ByteArray, directoryUri: kotlin.String, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Long`
  core$_.int saveBytesAs(
    jni$_.JByteArray bs,
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    core$_.int i,
    ProgressCallback progressCallback,
  ) {
    final _$bs = bs.reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$progressCallback = progressCallback.reference;
    return _saveBytesAs(
      reference.pointer,
      _id_saveBytesAs.pointer,
      _$bs.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      i,
      _$progressCallback.pointer,
    ).long;
  }

  static final _id_saveFileAs = FileSaver._class.instanceMethodId(
    r'saveFileAs',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)J',
  );

  static final _saveFileAs =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveFileAs(filePath: kotlin.String, directoryUri: kotlin.String, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Long`
  core$_.int saveFileAs(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JString string4,
    core$_.int i,
    ProgressCallback progressCallback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4.reference;
    final _$progressCallback = progressCallback.reference;
    return _saveFileAs(
      reference.pointer,
      _id_saveFileAs.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      _$string4.pointer,
      i,
      _$progressCallback.pointer,
    ).long;
  }

  static final _id_saveNetworkAs = FileSaver._class.instanceMethodId(
    r'saveNetworkAs',
    r'(Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)J',
  );

  static final _saveNetworkAs =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveNetworkAs(url: kotlin.String, headersJson: kotlin.String?, timeoutMs: kotlin.Int, directoryUri: kotlin.String, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Long`
  core$_.int saveNetworkAs(
    jni$_.JString string,
    jni$_.JString? string1,
    core$_.int i,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JString string4,
    jni$_.JString string5,
    core$_.int i1,
    ProgressCallback progressCallback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4.reference;
    final _$string5 = string5.reference;
    final _$progressCallback = progressCallback.reference;
    return _saveNetworkAs(
      reference.pointer,
      _id_saveNetworkAs.pointer,
      _$string.pointer,
      _$string1.pointer,
      i,
      _$string2.pointer,
      _$string3.pointer,
      _$string4.pointer,
      _$string5.pointer,
      i1,
      _$progressCallback.pointer,
    ).long;
  }

  static final _id_openWriteSession = FileSaver._class.instanceMethodId(
    r'openWriteSession',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;IJLcom/vanvixi/file_saver_ffi/models/ProgressCallback;)V',
  );

  static final _openWriteSession =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun openWriteSession(baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, saveLocationIndex: kotlin.Int, subDir: kotlin.String?, conflictMode: kotlin.Int, totalSize: kotlin.Long, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Unit`
  void openWriteSession(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    core$_.int i,
    jni$_.JString? string3,
    core$_.int i1,
    core$_.int j,
    ProgressCallback progressCallback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$progressCallback = progressCallback.reference;
    _openWriteSession(
      reference.pointer,
      _id_openWriteSession.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      i,
      _$string3.pointer,
      i1,
      j,
      _$progressCallback.pointer,
    ).check();
  }

  static final _id_openWriteSessionAs = FileSaver._class.instanceMethodId(
    r'openWriteSessionAs',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IJLcom/vanvixi/file_saver_ffi/models/ProgressCallback;)V',
  );

  static final _openWriteSessionAs =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun openWriteSessionAs(directoryUri: kotlin.String, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, conflictMode: kotlin.Int, totalSize: kotlin.Long, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Unit`
  void openWriteSessionAs(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    core$_.int i,
    core$_.int j,
    ProgressCallback progressCallback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$progressCallback = progressCallback.reference;
    _openWriteSessionAs(
      reference.pointer,
      _id_openWriteSessionAs.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      i,
      j,
      _$progressCallback.pointer,
    ).check();
  }

  static final _id_writeChunk = FileSaver._class.instanceMethodId(
    r'writeChunk',
    r'(J[BLcom/vanvixi/file_saver_ffi/models/ProgressCallback;)V',
  );

  static final _writeChunk =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun writeChunk(sessionId: kotlin.Long, data: kotlin.ByteArray, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Unit`
  void writeChunk(
    core$_.int j,
    jni$_.JByteArray bs,
    ProgressCallback progressCallback,
  ) {
    final _$bs = bs.reference;
    final _$progressCallback = progressCallback.reference;
    _writeChunk(
      reference.pointer,
      _id_writeChunk.pointer,
      j,
      _$bs.pointer,
      _$progressCallback.pointer,
    ).check();
  }

  static final _id_flushSession = FileSaver._class.instanceMethodId(
    r'flushSession',
    r'(JLcom/vanvixi/file_saver_ffi/models/ProgressCallback;)V',
  );

  static final _flushSession =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int64, jni$_.Pointer<jni$_.Void>)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun flushSession(sessionId: kotlin.Long, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Unit`
  void flushSession(core$_.int j, ProgressCallback progressCallback) {
    final _$progressCallback = progressCallback.reference;
    _flushSession(
      reference.pointer,
      _id_flushSession.pointer,
      j,
      _$progressCallback.pointer,
    ).check();
  }

  static final _id_closeSession = FileSaver._class.instanceMethodId(
    r'closeSession',
    r'(JLcom/vanvixi/file_saver_ffi/models/ProgressCallback;)V',
  );

  static final _closeSession =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int64, jni$_.Pointer<jni$_.Void>)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun closeSession(sessionId: kotlin.Long, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Unit`
  void closeSession(core$_.int j, ProgressCallback progressCallback) {
    final _$progressCallback = progressCallback.reference;
    _closeSession(
      reference.pointer,
      _id_closeSession.pointer,
      j,
      _$progressCallback.pointer,
    ).check();
  }

  static final _id_cancelSession = FileSaver._class.instanceMethodId(
    r'cancelSession',
    r'(J)V',
  );

  static final _cancelSession =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int64,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun cancelSession(sessionId: kotlin.Long): kotlin.Unit`
  void cancelSession(core$_.int j) {
    _cancelSession(reference.pointer, _id_cancelSession.pointer, j).check();
  }
}

final class $FileSaver$Type$ extends jni$_.JType<FileSaver> {
  @jni$_.internal
  const $FileSaver$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/FileSaver;';
}

/// from: `com.vanvixi.file_saver_ffi.models.ProgressCallback`
extension type ProgressCallback._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/models/ProgressCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ProgressCallback> type = $ProgressCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $ProgressCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onEvent(IDLjava/lang/String;Ljava/lang/String;)V') {
        _$impls[$p]!.onEvent(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JDouble).toDartDouble(releaseOriginal: true),
          ($a![2] as jni$_.JString?),
          ($a![3] as jni$_.JString?),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $ProgressCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.vanvixi.file_saver_ffi.models.ProgressCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onEvent$async)
          r'onEvent(IDLjava/lang/String;Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory ProgressCallback.implement($ProgressCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<ProgressCallback>();
  }
}

extension ProgressCallback$$Methods on ProgressCallback {
  static final _id_onEvent = ProgressCallback._class.instanceMethodId(
    r'onEvent',
    r'(IDLjava/lang/String;Ljava/lang/String;)V',
  );

  static final _onEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Double,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onEvent(eventType: kotlin.Int, progress: kotlin.Double, data: kotlin.String?, message: kotlin.String?): kotlin.Unit`
  void onEvent(
    core$_.int i,
    core$_.double d,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _onEvent(
      reference.pointer,
      _id_onEvent.pointer,
      i,
      d,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }
}

abstract base mixin class $ProgressCallback {
  factory $ProgressCallback({
    required void Function(
      core$_.int i,
      core$_.double d,
      jni$_.JString? string,
      jni$_.JString? string1,
    )
    onEvent,
    core$_.bool onEvent$async,
  }) = _$ProgressCallback;

  void onEvent(
    core$_.int i,
    core$_.double d,
    jni$_.JString? string,
    jni$_.JString? string1,
  );
  core$_.bool get onEvent$async => false;
}

final class _$ProgressCallback with $ProgressCallback {
  _$ProgressCallback({
    required void Function(
      core$_.int i,
      core$_.double d,
      jni$_.JString? string,
      jni$_.JString? string1,
    )
    onEvent,
    this.onEvent$async = false,
  }) : _onEvent = onEvent;

  final void Function(
    core$_.int i,
    core$_.double d,
    jni$_.JString? string,
    jni$_.JString? string1,
  )
  _onEvent;
  final core$_.bool onEvent$async;

  void onEvent(
    core$_.int i,
    core$_.double d,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    return _onEvent(i, d, string, string1);
  }
}

final class $ProgressCallback$Type$ extends jni$_.JType<ProgressCallback> {
  @jni$_.internal
  const $ProgressCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/vanvixi/file_saver_ffi/models/ProgressCallback;';
}
