// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class FileSaverFFI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FileSaverFFI(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FileSaverFFI.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initialize Dart API for NativePort communication.
  /// Must be called before using file_saver_save_bytes.
  ///
  /// @param data Pointer from NativeApi.initializeApiDLData
  /// @return 0 on success, -1 on failure
  int initDartApiDl(ffi.Pointer<ffi.Void> data) {
    return _initDartApiDl(data);
  }

  late final _initDartApiDlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'file_saver_init_dart_api_dl',
      );
  late final _initDartApiDl =
      _initDartApiDlPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> init() {
    return _init();
  }

  late final _initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'file_saver_init',
      );
  late final _init = _initPtr.asFunction<ffi.Pointer<ffi.Void> Function()>();

  void dispose(ffi.Pointer<ffi.Void> instance) {
    return _dispose(instance);
  }

  late final _disposePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'file_saver_dispose',
      );
  late final _dispose =
      _disposePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Cancel an ongoing save operation.
  ///
  /// @param tokenId Token ID returned from file_saver_save_bytes or file_saver_save_file
  void cancel(int tokenId) {
    return _cancel(tokenId);
  }

  late final _cancelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64)>>(
        'file_saver_cancel',
      );
  late final _cancel = _cancelPtr.asFunction<void Function(int)>();

  /// Save file bytes asynchronously with progress reporting via NativePort.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param fileData Byte array of file content
  /// @param fileDataLength Length of fileData
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param mimeType MIME type string
  /// @param saveLocation Save location index (0-4)
  /// @param subDir Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveBytes(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Uint8> fileData,
    int fileDataLength,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int native_port,
  ) {
    return _saveBytes(
      instance,
      fileData,
      fileDataLength,
      baseFileName,
      extension,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      native_port,
    );
  }

  late final _saveBytesPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Int64,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_bytes');
  late final _saveBytes =
      _saveBytesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save file from source path asynchronously with progress reporting via
  /// NativePort.
  ///
  /// Reads source file in chunks without loading into memory - suitable for large
  /// files. Handles security-scoped resources (Files app) and iCloud file
  /// downloads.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param filePath Source file path (file:// URI)
  /// @param baseFileName Target file name without extension
  /// @param extension File extension without dot
  /// @param mimeType MIME type string
  /// @param saveLocation Save location index (0-1 for iOS)
  /// @param subDir Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveFile(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> filePath,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int native_port,
  ) {
    return _saveFile(
      instance,
      filePath,
      baseFileName,
      extension,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      native_port,
    );
  }

  late final _saveFilePtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_file');
  late final _saveFile =
      _saveFilePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save file from network URL asynchronously with progress reporting via
  /// NativePort.
  ///
  /// Downloads file at native level to avoid double storage:
  /// - Documents: Downloads directly to target path
  /// - Photos: Downloads to tmp, saves to Photos Library, deletes tmp
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param urlString URL to download from
  /// @param headersJson Optional JSON string of HTTP headers (can be NULL)
  /// @param timeoutSeconds Timeout in seconds for network request
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param mimeType MIME type string
  /// @param saveLocation Save location index (0-1 for iOS)
  /// @param subDir Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveNetwork(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> urlString,
    ffi.Pointer<ffi.Char> headersJson,
    int timeoutSeconds,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int native_port,
  ) {
    return _saveNetwork(
      instance,
      urlString,
      headersJson,
      timeoutSeconds,
      baseFileName,
      extension,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      native_port,
    );
  }

  late final _saveNetworkPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_network');
  late final _saveNetwork =
      _saveNetworkPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save bytes to user-selected directory (saveAs).
  ///
  /// Saves file bytes to a directory previously selected via DirPicker.pick() (package:dir_picker).
  /// Uses security-scoped resource access for the selected directory.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param fileData Byte array of file content
  /// @param fileDataLength Length of fileData
  /// @param directoryUri Directory URI from DirPicker.pick() (package:dir_picker)
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveBytesAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Uint8> fileData,
    int fileDataLength,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    int conflictMode,
    int native_port,
  ) {
    return _saveBytesAs(
      instance,
      fileData,
      fileDataLength,
      directoryUri,
      baseFileName,
      extension,
      conflictMode,
      native_port,
    );
  }

  late final _saveBytesAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Int64,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_bytes_as');
  late final _saveBytesAs =
      _saveBytesAsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save file to user-selected directory (saveAs).
  ///
  /// Copies a file to a directory previously selected via DirPicker.pick() (package:dir_picker).
  /// Uses security-scoped resource access for the selected directory.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param filePath Source file path (file:// URI)
  /// @param directoryUri Directory URI from DirPicker.pick() (package:dir_picker)
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveFileAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> filePath,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    int conflictMode,
    int native_port,
  ) {
    return _saveFileAs(
      instance,
      filePath,
      directoryUri,
      baseFileName,
      extension,
      conflictMode,
      native_port,
    );
  }

  late final _saveFileAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_file_as');
  late final _saveFileAs =
      _saveFileAsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save network file to user-selected directory (saveAs).
  ///
  /// Downloads and saves a file to a directory previously selected via
  /// DirPicker.pick() (package:dir_picker). Uses security-scoped resource access.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param urlString URL to download from
  /// @param headersJson Optional JSON string of HTTP headers (can be NULL)
  /// @param timeoutSeconds Timeout in seconds for network request
  /// @param directoryUri Directory URI from DirPicker.pick() (package:dir_picker)
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveNetworkAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> urlString,
    ffi.Pointer<ffi.Char> headersJson,
    int timeoutSeconds,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    int conflictMode,
    int native_port,
  ) {
    return _saveNetworkAs(
      instance,
      urlString,
      headersJson,
      timeoutSeconds,
      directoryUri,
      baseFileName,
      extension,
      conflictMode,
      native_port,
    );
  }

  late final _saveNetworkAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_network_as');
  late final _saveNetworkAs =
      _saveNetworkAsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Opens the saved file with the appropriate system viewer.
  ///
  /// - iOS `file://`: Opens a QuickLook inline preview via UIDocumentInteractionController.
  /// Falls back to UIActivityViewController (share/open-with sheet) for
  /// file types without a QuickLook provider.
  /// - iOS `ph://`:   Resolves the PHAsset's underlying file URL (image via
  /// PHContentEditingInput, video/audio via AVURLAsset), then presents
  /// a QuickLook preview with the same fallback as above.
  /// ph:// is an internal Photos framework scheme — UIApplication.shared.open()
  /// does not work with it.
  /// - macOS: Opens the file with NSWorkspace.shared.open().
  ///
  /// @param uri URI string returned from save operations (file://, ph://)
  bool openFile(ffi.Pointer<ffi.Char> uri) {
    return _openFile(uri);
  }

  late final _openFilePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>(
        'file_saver_open_file',
      );
  late final _openFile =
      _openFilePtr.asFunction<bool Function(ffi.Pointer<ffi.Char>)>();

  /// Checks whether the file at the given URI is accessible for reading.
  ///
  /// - iOS `file://`: FileManager.isReadableFile(atPath:)
  /// - iOS `ph://`: PHAsset.fetchAssets — check if asset exists in Photos Library
  /// - macOS `file://`: FileManager.isReadableFile(atPath:)
  ///
  /// @param uri URI string returned from save operations (file://, ph://)
  /// @return true if the file is accessible, false otherwise
  bool canOpenFile(ffi.Pointer<ffi.Char> uri) {
    return _canOpenFile(uri);
  }

  late final _canOpenFilePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>(
        'file_saver_can_open_file',
      );
  late final _canOpenFile =
      _canOpenFilePtr.asFunction<bool Function(ffi.Pointer<ffi.Char>)>();

  /// Opens a streaming write session to a platform save location.
  ///
  /// iOS photos location: supported for images and videos only (chunks written to a temp file,
  /// committed to the Photos Library on close). Audio and custom types send an error.
  ///
  /// Messages sent to native_port:
  /// - Session opened:  [3, sessionId]   (sessionId as string)
  /// - Error:           [2, errorCode, errorMessage]
  ///
  /// @param instance    FileSaver instance from file_saver_init
  /// @param baseFileName File name without extension
  /// @param ext         File extension without dot
  /// @param mimeType    MIME type string
  /// @param saveLocation Save location index
  /// @param subDir      Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param totalSize   Total expected bytes (-1 if unknown)
  /// @param native_port Dart NativePort for result delivery
  void openWrite(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> ext,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int totalSize,
    int native_port,
  ) {
    return _openWrite(
      instance,
      baseFileName,
      ext,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      totalSize,
      native_port,
    );
  }

  late final _openWritePtr = _lookup<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
        ffi.Int64,
      )
    >
  >('file_saver_open_write');
  late final _openWrite =
      _openWritePtr
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
              int,
            )
          >();

  /// Opens a streaming write session to a user-selected directory.
  ///
  /// Messages sent to native_port:
  /// - Session opened:  [3, sessionId]   (sessionId as string)
  /// - Error:           [2, errorCode, errorMessage]
  ///
  /// @param instance    FileSaver instance from file_saver_init
  /// @param directoryUri Directory URI from DirPicker.pick()
  /// @param baseFileName File name without extension
  /// @param ext         File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param totalSize   Total expected bytes (-1 if unknown)
  /// @param native_port Dart NativePort for result delivery
  void openWriteAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> ext,
    int conflictMode,
    int totalSize,
    int native_port,
  ) {
    return _openWriteAs(
      instance,
      directoryUri,
      baseFileName,
      ext,
      conflictMode,
      totalSize,
      native_port,
    );
  }

  late final _openWriteAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
        ffi.Int64,
      )
    >
  >('file_saver_open_write_as');
  late final _openWriteAs =
      _openWriteAsPtr
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
              int,
            )
          >();

  /// Writes a chunk of data to an open write session.
  ///
  /// Messages sent to native_port:
  /// - Chunk ACK:  [1, bytesWritten]
  /// - Error:      [2, errorCode, errorMessage]
  ///
  /// @param sessionId  Session ID from file_saver_open_write[_as]
  /// @param data       Byte array to write
  /// @param dataLength Length of data in bytes
  /// @param native_port Dart NativePort for result delivery
  void writeChunk(
    int sessionId,
    ffi.Pointer<ffi.Uint8> data,
    int dataLength,
    int native_port,
  ) {
    return _writeChunk(sessionId, data, dataLength, native_port);
  }

  late final _writeChunkPtr = _lookup<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Uint64,
        ffi.Pointer<ffi.Uint8>,
        ffi.Int64,
        ffi.Int64,
      )
    >
  >('file_saver_write_chunk');
  late final _writeChunk =
      _writeChunkPtr
          .asFunction<void Function(int, ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Flushes write buffers for an open write session.
  ///
  /// Messages sent to native_port:
  /// - Flush ACK:  [1, bytesWritten]
  /// - Error:      [2, errorCode, errorMessage]
  ///
  /// @param sessionId  Session ID from file_saver_open_write[_as]
  /// @param native_port Dart NativePort for result delivery
  void flushWrite(int sessionId, int native_port) {
    return _flushWrite(sessionId, native_port);
  }

  late final _flushWritePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64, ffi.Int64)>>(
        'file_saver_flush_write',
      );
  late final _flushWrite = _flushWritePtr.asFunction<void Function(int, int)>();

  /// Closes and finalizes an open write session.
  ///
  /// Messages sent to native_port:
  /// - Success:  [3, fileUri]
  /// - Error:    [2, errorCode, errorMessage]
  ///
  /// @param sessionId  Session ID from file_saver_open_write[_as]
  /// @param native_port Dart NativePort for result delivery
  void closeWrite(int sessionId, int native_port) {
    return _closeWrite(sessionId, native_port);
  }

  late final _closeWritePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64, ffi.Int64)>>(
        'file_saver_close_write',
      );
  late final _closeWrite = _closeWritePtr.asFunction<void Function(int, int)>();

  /// Cancels and discards an open write session (fire-and-forget).
  ///
  /// Closes the FileHandle and deletes the partial file.
  /// No callback — caller should complete with CancelledException.
  ///
  /// @param sessionId  Session ID from file_saver_open_write[_as]
  void cancelWrite(int sessionId) {
    return _cancelWrite(sessionId);
  }

  late final _cancelWritePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64)>>(
        'file_saver_cancel_write',
      );
  late final _cancelWrite = _cancelWritePtr.asFunction<void Function(int)>();
}
